name: Create_App_Heroku

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm install --global heroku
          yarn global add heroku
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: "YOUR EMAIL"
      - name: Create App in Heroku
        run: |
          heroku create